--- #YAML:1.0
name:                Roman
version:             1.20
abstract:            Perl module for conversion between Roman and Arabic numerals.
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Alexandr Ciornii <alexchorny AT gmail.com>
