--- #YAML:1.0
name:               Roman
version:            1.23
abstract:           Perl module for conversion between Roman and Arabic numerals.
author:
    - Alexandr Ciornii <alexchorny AT gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Exporter:    5.57
    perl:        5.006
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
